services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: music_navidrome
    restart: always
    expose:
      - 4533
    volumes:
      - ./data:/data
      - ${MUSIC_FOLDER}:/music:ro
    environment:
      - ND_MUSICFOLDER=/music
      - ND_DATAFOLDER=/data
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=4533
    networks:
      - default
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
